language: node_js
node_js:
  - "15.9.0"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - echo "DB_HOST=127.0.0.1\nDB_PORT=3306\nDB_USERNAME=travis\nDB_PASSWORD=\nDB_DATABASE=test\nDB_SYNCHRONIZE=true\n\nGRAPHQL_DEBUG=true\nGRAPHQL_PLAYGROUND=true\n\nJWT_SECRET=s3cret\nPORT=8000\n\nNODE_ENV=development\n\nHASH_ALGORITHM=SHA256\nHASH_SALT_ROUNDS=50\n" > .env